### ISSUE TITLE
SSE streams limited per client IP

### ISSUE THREAD

**Issue by Vaelatern** [piqoni/inxidents#1]
If I have 21 services being watched, and I put this behind an apache reverse proxy, I will get a hang on one of the 21 services, probably the last one.

I forget if this is easily fixed with configuration, but it is a downside to SSE.

**Comment by piqoni** [comment]
Thanks for the feedback. Strange, as one of the advantages with SSE were less proxy issues according to this source: https://blog.bitsrc.io/websockets-vs-server-sent-events-968659ab0870 (and other sources I checked before opting for SSE, so SSE should have less issues than web sockets in general). 

Im not familiar with apache limitation but likely can be indeed solved with configuration, maybe this is relevant: 
https://support.yumaworks.com/support/solutions/articles/1000229870-how-do-i-configure-apache2-web-server-to-support-server-sent-event-sse-

**Comment by piqoni** [comment]
Closing as no reproduce-able issue for the time being. :)
